### ISSUE TITLE
Archlinux Install

### ISSUE THREAD

**Issue by trevortknguyen** [jaredallard/notion-app#5]
I clone the repo, change directories to the repo. I run `makepkg -si` and enter in my password. I type 'Y' to confirm the install. It's installed.

I type `notion` into the console and get this error.

```
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module '/opt/notion/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

**Comment by jaredallard** [comment]
Interesting, I'll see if I can reproduce it!

**Comment by jaredallard** [comment]
I would highly recommend on Arch you use the `notion-app` package though, which was inspired by this project and uses some of this "code". They knew how to make a much better archlinux compatible setup than I did!

**Comment by jaredallard** [comment]
We've removed our makepkg in favor of `notion-app`, so I'm going to close this!
